[package]
name = "durable"
version = "0.1.0"
edition = "2024"
license = "LicenseRef-Proprietary"

[dependencies]
sqlx = { version = "0.9.0-alpha.1", features = ["sqlx-toml", "postgres", "runtime-tokio", "chrono", "tls-rustls"] }
